name: Release Checker

on:
  pull_request_target:
    paths: [ 'version.json' ]
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-check:
    uses: ipdxco/unified-github-workflows/.github/workflows/release-check.yml@aggregate-release-json
  release-check-followup:
    needs: [release-check]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ needs.release-check.outputs.json }}'
        shell: bash
    
