name: Releaser

on:
  push:
    paths: [ 'version.json' ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  releaser:
    uses: ipdxco/unified-github-workflows/.github/workflows/releaser.yml@feat/subpackages
  releaser-followup:
    needs: [releaser]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ needs.releaser.outputs.json }}'
        shell: bash
      - run: jq . <<< '${{ fromJSON(needs.releaser.outputs.json) }}'
        shell: bash
